#!/usr/bin/env bash
# Install Nginx and modify the index.html 

sudo apt-get -y update
sudo apt-get -y install nginx
sudo cp /var/www/html/index.nginx-debian.html default_0
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
