#!/usr/bin/env bash
# Install a web server and configure to redirect

sudo apt-get -y update
sudo apt-get -y install nginx
sudo mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup
sudo cat << EOF | sudo tee /etc/nginx/nginx.conf
events {

}

http {

  server {
    listen 80;
    server_name musaoluwamayowa.tech;

    location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
  
  }
}
EOF
sudo nginx -t
sudo nginx -s reload
sudo service nginx start
