#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/err_404.html > /dev/null
sudo sed -i "46i \\\terror_page 404 /err_404.html;\n" /etc/nginx/sites-available/default
sudo nginx -s reload
