#!/usr/bin/env bash
# Install nginx server and configure it to requirements

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/errr.html
sed -i "46i error_page 404 /errr.html;" /etc/nginx/sites-available/default
sudo nginx -s reload
