#!/usr/bin/env bash
# Configure NGINX to responsd with custom header

sudo apt-get -y update
sudo apt-get install -y nginx
sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf_copy
sudo sed -i '16iadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
