#!/usr/bin/env bash
# Install HAproxy and configure it to balances two web servers

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*

cat << EOF |sudo tee -a /etc/haproxy/haproxy.cfg
frontend main
    bind *:80
    mode http
    default_backend   web

backend web
    balance   roundrobin
    server 18627-web-01 3.238.25.45:80 check
    server 18627-web-02 44.192.21.5:80 check
EOF
sudo systemctl start haproxy
sudo systemctl enable haproxy
sudo systemctl restart haproxy
