#!/usr/bin/env bash
# Install HAproxy and configure it to balances two web servers

set -x # Enable xtrace
set -eo pipefail # Causes the script to exit on error

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy=2.6.\*

echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
cat << EOF |sudo tee -a /etc/haproxy/haproxy.cfg
frontend main
    bind *:80
    mode http
    timeout client 20s
    default_backend  web

backend web
    mode http
    timeout connect 20s
    timeout server 20s
    balance   roundrobin
    server 18627-web-01 3.84.237.196:80 check
    server 18627-web-02 3.80.19.23:80 check
EOF
sudo service haproxy restart
