#!/usr/bin/env bash
# This script create and delete a file using signals
trap 'echo "I hate the kill command" ; sudo rm /var/run/myscript.pid && exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm /var/run/myscript.pid && exit 0' SIGQUIT
sudo echo $$ | sudo tee /var/run/myscript.pid > /dev/null
while :
do
	echo "To infinty and beyond"
	sleep 2
done
