#!/usr/bin/env bash
# This script displays Best School 10 times but display Hi after the 9th iteration

i=0
while [ $i -ne 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i += 1))
	echo "Best School"
done
