#!/usr/bin/env bash
# This script displays some messages at different iterations

i=0
while [ $i -ne 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i += 1))
done
