#!/usr/bin/env bash
# Displays the property of school file

file=./school
if [ -e "$file" ]
then
	echo "school file exits"
	if [ ! -s "$file" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$file" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
