#!/usr/bin/env bash
# This script changes the IP address of localhost and facebook.com on Ubuntu server
cp /etc/hosts ~/hosts.new
sed ... ~/hosts.new
cp -f ~/hosts.new /etc/hosts

sed -i 's/.*localhost.*/127.0.0.2	localhost/g' ~/hosts.new
sed -i 's/.*facebook.com.*/8.8.8.8	facebook.com/g' ~/hosts.new
