#!/usr/bin/env bash
# This script changes home IP address
cp /etc/hosts ~/hosts.new
sed ... ~/hosts.new
cp -f ~/hosts.new /etc/hosts

sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
sed -i 's/157.240.11.35/8.8.8.8/g' ~/hosts.new
