#!/usr/bin/env bash
# This script changes the IP address of localhost and facebook.com on Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost.*/127.0.0.2	localhost/g' ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
