#!/usr/bin/env bash
# Run nginx as nginx
sudo apt-get update
sudo apt-get -y install nginx
echo "user nginx;" | sudo tee -a /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx restart
